### ISSUE TITLE
how to create index using for this demo

### ISSUE THREAD

**Issue by quezhihui** [thecarlo/elastic-kibana-netcore-serilog#1]
![default](https://user-images.githubusercontent.com/13636503/42426281-5ba30d32-8359-11e8-9eac-e0f1dd40009b.png)

I use postman to post data

**Comment by thecarlo** [comment]
Did you read the repo's Readme?

Full details in the blog post that is referenced in the readme.

**Comment by quezhihui** [comment]
Thank for your reply.
I have read it and get record succeed.
![default](https://user-images.githubusercontent.com/13636503/42440894-71c09626-8399-11e8-856e-1c4737bd47f7.png)


Now I want to know why the index name is "logstach-2018.07.09" .
No config in your code except uri. 
I want use custom args but do not know how todo (such as index name "log_oa_2018.07")


![default](https://user-images.githubusercontent.com/13636503/42441128-1df85ba4-839a-11e8-888d-1ff93173155f.png)

**Comment by thecarlo** [comment]
Why not just use a wildcard like logstash-* ?

**Comment by thecarlo** [comment]
resolved
