### ISSUE TITLE
How store object using params args?

### ISSUE THREAD

**Issue by btbensoft** [thecarlo/elastic-kibana-netcore-serilog#2]
Hello

Thankyou for your code. I got a question for you. How can i log specific object to ELK using .net Logger as :

```
public CommandResult Example(MyObject myObject)
{
        try
        {
             logger.LogInformation("myObject is : ", myObject); // <== log my object as json
         }
         catch (System.Exception ex)
         {
             logger.LogError(ex, "error");
         }

         return null;
}
```

How to use args :
![image](https://user-images.githubusercontent.com/36570423/46794608-7f302080-cd48-11e8-810b-9859278a53d0.png)

Or i should use an other way?

Thanks a lot

**Comment by thecarlo** [comment]
You can log it as such:

`_logger.LogInformation("My Logged Object: {@myLoggedObject}", myObject);`
