### ISSUE TITLE
elasticsearch, kibana 7.0.1

### ISSUE THREAD

**Issue by abrasat** [thecarlo/elastic-kibana-netcore-serilog#3]
I tried to change the versions of elasticsearch and kibana from the docker-compose.yml file from version 6.2.4 to the newest version 7.0.1 (I previously removed all containers from the docker).
When starting the containers from Windows 10 powershell prompt with the command "docker-compose up -d" the elasticsearch container starts but exits after a couple of seconds (kibana container is running further). I attached a terminal to the elasticsearch container and saw the following error message:

...
ERROR: [1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
...

With the "original" docker-compose.yml file (references the 6.2.4 elasticsearch and kibana versions) the containers are working fine.
What must be changed to get the containers working with the 7.0.1 version?

**Comment by thecarlo** [comment]
Thanks for letting me know. I'll investigate and update the repo.

**Comment by thecarlo** [comment]
This has now been resolved. Upgraded to Elastic Search + Kibana 7.2.0
