### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by lexon0011** [thecarlo/elastic-kibana-netcore-serilog#4]
After starting the docker image and navigating to http://localhost:5601 I get the following error:
Kibana server is not ready yet

I use docker on Windows 10.

Any ideas?

Regards

**Comment by lexon0011** [comment]
I could fix it by change a setting in the `docker-compose.yml`:

![2019-09-03 13_05_30-Window](https://user-images.githubusercontent.com/16290662/64168365-a3f32200-ce4b-11e9-82ce-23f146ccbf25.png)

**Comment by thecarlo** [comment]
Upgraded to new version and pushed changes
